use_frameworks!

target 'BMLTiOSLib_Example' do
  pod 'BMLTiOSLib', :path => '../'

  target 'BMLTiOSLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
