disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- function_body_length
- trailing_whitespace
- type_name
- file_length
- type_body_length

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:

line_length:
- 399 # warning
- 300 # error

cyclomatic_complexity:
- 12 # warning
- 13 # error
